// REQUEST

export const REQUEST_CREATE_PLAN_TEMPLATE = "REQUEST_CREATE_PLAN_TEMPLATE";
export const REQUEST_CREATE_PLAN_TEMPLATE_SUCCESS = "REQUEST_CREATE_PLAN_TEMPLATE_SUCCESS";
export const REQUEST_CREATE_PLAN_TEMPLATE_FAILURE = "REQUEST_CREATE_PLAN_TEMPLATE_FAILURE";

export const REQUEST_GET_PLAN_TEMPLATE_LIST = "REQUEST_GET_PLAN_TEMPLATE_LIST";
export const REQUEST_GET_PLAN_TEMPLATE_LIST_SUCCESS = "REQUEST_GET_PLAN_TEMPLATE_LIST_SUCCESS";
export const REQUEST_GET_PLAN_TEMPLATE_LIST_FAILURE = "REQUEST_GET_PLAN_TEMPLATE_LIST_FAILURE";

export const REQUEST_GET_PLAN_TEMPLATE = "REQUEST_GET_PLAN_TEMPLATE";
export const REQUEST_GET_PLAN_TEMPLATE_SUCCESS = "REQUEST_GET_PLAN_TEMPLATE_SUCCESS";
export const REQUEST_GET_PLAN_TEMPLATE_FAILURE = "REQUEST_GET_PLAN_TEMPLATE_FAILURE";

export const REQUEST_UPDATE_PLAN_TEMPLATE = "REQUEST_UPDATE_PLAN_TEMPLATE";
export const REQUEST_UPDATE_PLAN_TEMPLATE_SUCCESS = "REQUEST_UPDATE_PLAN_TEMPLATE_SUCCESS";
export const REQUEST_UPDATE_PLAN_TEMPLATE_FAILURE = "REQUEST_UPDATE_PLAN_TEMPLATE_FAILURE";

export const REQUEST_DELETE_PLAN_TEMPLATE = "REQUEST_DELETE_PLAN_TEMPLATE";
export const REQUEST_DELETE_PLAN_TEMPLATE_SUCCESS = "REQUEST_DELETE_PLAN_TEMPLATE_SUCCESS";
export const REQUEST_DELETE_PLAN_TEMPLATE_FAILURE = "REQUEST_DELETE_PLAN_TEMPLATE_FAILURE";

export const REQUEST_CREATE_TASK_TEMPLATE = "REQUEST_CREATE_TASK_TEMPLATE";
export const REQUEST_CREATE_TASK_TEMPLATE_SUCCESS = "REQUEST_CREATE_TASK_TEMPLATE_SUCCESS";
export const REQUEST_CREATE_TASK_TEMPLATE_FAILURE = "REQUEST_CREATE_TASK_TEMPLATE_FAILURE";

export const REQUEST_GET_TASK_TEMPLATE = "REQUEST_GET_TASK_TEMPLATE";
export const REQUEST_GET_TASK_TEMPLATE_SUCCESS = "REQUEST_GET_TASK_TEMPLATE_SUCCESS";
export const REQUEST_GET_TASK_TEMPLATE_FAILURE = "REQUEST_GET_TASK_TEMPLATE_FAILURE";

export const REQUEST_UPDATE_TASK_TEMPLATE = "REQUEST_UPDATE_TASK_TEMPLATE";
export const REQUEST_UPDATE_TASK_TEMPLATE_SUCCESS = "REQUEST_UPDATE_TASK_TEMPLATE_SUCCESS";
export const REQUEST_UPDATE_TASK_TEMPLATE_FAILURE = "REQUEST_UPDATE_TASK_TEMPLATE_FAILURE";

export const REQUEST_DELETE_TASK_TEMPLATE = "REQUEST_DELETE_TASK_TEMPLATE";
export const REQUEST_DELETE_TASK_TEMPLATE_SUCCESS = "REQUEST_DELETE_TASK_TEMPLATE_SUCCESS";
export const REQUEST_DELETE_TASK_TEMPLATE_FAILURE = "REQUEST_DELETE_TASK_TEMPLATE_FAILURE";
