export const ADD_NEW_TASK_TEMPLATE = "ADD_NEW_TASK_TEMPLATE";
export const EDIT_NEW_TASK_TEMPLATE = "EDIT_NEW_TASK_TEMPLATE";
export const UP_NEW_TASK_TEMPLATE = "UP_NEW_TASK_TEMPLATE";
export const DOWN_NEW_TASK_TEMPLATE = "DOWN_NEW_TASK_TEMPLATE";
export const REMOVE_NEW_TASK_TEMPLATE = "REMOVE_NEW_TASK_TEMPLATE";
export const TOGGLE_NEW_TASK_TEMPLATE = "TOGGLE_NEW_TASK_TEMPLATE";

export const REQUEST_POST_PLAN_TEMPLATE = "REQUEST_POST_PLAN_TEMPLATE";
export const SUCCESS_POST_PLAN_TEMPLATE = "SUCCESS_POST_PLAN_TEMPLATE";
export const FAILURE_POST_PLAN_TEMPLATE = "FAILURE_POST_PLAN_TEMPLATE";

export const SET_ALERT = "SET_ALERT";